name: google_doc
description: Collaborative Rich Text Editing Experience with Flutter Web and Appwrite
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  logging: ^1.1.1
  flutter_riverpod: ^2.2.0
  routemaster: ^1.0.1
  equatable: ^2.0.5
  flutter_quill: ^6.4.4 # 4.1.0
  appwrite: ^8.2.2
  tuple: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
