name: picogram
description: Sharing Image and Video
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  collection: ^1.16.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter

  flutter_facebook_auth: ^5.0.7
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.3.0
  google_sign_in: ^5.4.3
  hooks_riverpod: ^2.1.3
  image: ^4.0.8
  image_picker: ^0.8.6
  intl: ^0.17.0
  lottie: ^2.2.0
  share_plus: ^6.3.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.4.10
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
  assets:
      - assets/animations/data_not_found.json
      - assets/animations/loading.json
      - assets/animations/empty.json
      - assets/animations/error.json
      - assets/animations/small_error.json
